name: Build and Deploy to Azure Container App

on:
  push:
    branches:
      - master  # Trigger on push to the 'master' branch (replace 'main' with 'master')

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1.6.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Using the AZURE_CREDENTIALS secret to log in

      - name: Log in to Azure Container Registry (ACR)
        run: az acr login --name ${{ secrets.ACR_NAME }}  # Ensure ACR_NAME is set in GitHub secrets

      - name: Build Docker image
        run: docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/loanapp:latest .

      - name: Push Docker image to ACR
        run: docker push ${{ secrets.ACR_NAME }}.azurecr.io/loanapp:latest

      - name: Deploy to Azure Container App
        run: |
          az containerapp create \
            --name loancalculatorapp \
            --resource-group loancalculatorapp \
            --image ${{ secrets.ACR_NAME }}.azurecr.io/loanapp:latest \
            --environment managedEnvironment-loancalculatora-8009 \
            --ingress external \
            --target-port 3000 \
            --registry-server ${{ secrets.ACR_NAME }}.azurecr.io \
            --registry-username ${{ secrets.ACR_USERNAME }} \
            --registry-password ${{ secrets.ACR_PASSWORD }}
